FROM continuumio/miniconda3

# Install missing cv2 dependency
RUN apt-get update
RUN apt-get install -y libgl1

# Create and activate the Conda environment
COPY aws/environment_foundation.yml .
RUN conda env create -f environment_foundation.yml

# Automatically activate the conda environment
RUN echo "source activate codem" >> ~/.bashrc
ENV PATH /opt/conda/envs/codem/bin:$PATH

# Install CODEM
COPY src ./src
COPY readme.md .
COPY setup.py .
RUN pip install .

# Lambda
RUN pip install awslambdaric
COPY aws/lambda_foundation_step.py .

ENTRYPOINT [ "python", "-m", "awslambdaric" ]
CMD [ "lambda_foundation_step.handler" ]
